### ISSUE TITLE
FileErrorNotFound

### ISSUE THREAD

**Issue by StormzCoder** [ProjectUnifree/unifree#34]
When I try to run the command I get this error 
```
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'config/'
```
If anyone knows how to fix it please let me know.

**Comment by Ishaanp24** [comment]
I found that the actual order of inputs is <config> <api key> <source directory> <target directory>, which is contrary to the provided readme. This solved FileNotFoundError

**Comment by Ishaanp24** [comment]
I found that the actual order of inputs is `<config> <api key> <source directory> <target directory>`
This solved FileNotFoundError

**Comment by bshikin** [comment]
@Ishaanp24 to confirm, is it windows?

**Comment by Ishaanp24** [comment]
Yes

**Comment by StormzCoder** [comment]
Thanks, that fixed it but now it's showing
```
< was unexpected at this time.
``` 
I don't know what's going on with it now.

**Comment by StormzCoder** [comment]
Back again it stopped, but now it's doing this when I try to run it.
```
Source directory is a git repo, assuming source directory is project source
Python is not found.
Please install Python and try again.
------------------------------------------------------------

C:\Users\(Username)\unifree>
```

**Comment by FlooferLand** [comment]
Try doing `python.exe --version` in the Windows terminal. If there is no output, you [need to install Python](https://www.python.org) to be able to run the interpreter for the language the project is written in.
If you have Python already installed, try changing `PYTHON_CMD` inside `launch.bat` to point to wherever `python.exe` was installed _(typically under `C:\Users\(Username)\AppData\Local\Programs\Python\Python311\python.exe\` if you install Python 3.11)_

The project is being developed quite fast, so that might have something to do with errors changing around. If you're still experiencing issues try [downloading the project again](https://github.com/ProjectUnifree/unifree/archive/refs/heads/main.zip)

**Comment by StormzCoder** [comment]
Nothing I'm trying is working.
