### ISSUE TITLE
[Proposal] Create migration to gamemaker

### ISSUE THREAD

**Issue by ayslan-gamedev** [ProjectUnifree/unifree#35]

**Comment by FlooferLand** [comment]
I'm not sure how plausible this would be, as it uses it's own proprietary GML language _(similar to JavaScript, but not really)_, and porting assets like game scenes would be impossible due to how GMS' works internally _(no concept of prefabs, etc)_
GameMaker Studio support isn't currently planned or considered, especially as it's not very requested.
